_MAJOR_VER = 0
_MINOR_VER = 5
_FIX_VER = 2
_BUILD_VER = 1
XEET_BASE_VERSION = f'{_MAJOR_VER}.{_MINOR_VER}.{_FIX_VER}'
XEET_FULL_VERSION = f'{_MAJOR_VER}.{_MINOR_VER}.{_FIX_VER}-{_BUILD_VER}'
__VERSION__ = XEET_FULL_VERSION
