#!/bin/bash
# This is confusing as hell, as we use xeet to test itself. The idea is to have a stable
# version of xeet outside the virtual environment, and use it to test the development
# version of xeet inside the virtual environment.

SCRIPT_FILE="$(readlink -f ${BASH_SOURCE[0]})"
SCRIPT_DIR="$(dirname $SCRIPT_FILE)"

# shellcheck disable=SC2164
cd ${SCRIPT_DIR}
xeet run -c xeet_qa.json --log-file=/tmp/xeet_qa.log "$@"
