#!/bin/bash
set -e
PROJ_ROOT=$(git rev-parse --show-toplevel 2>/dev/null)
if [ -z "${PROJ_ROOT}" ]; then
    echo "ERROR: Could not find project root. Are you in the project directory?"
    exit 1
fi

HERE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd ${HERE}

cmd="${PROJ_ROOT}/xeet run -c xeet.json $*"
echo "Running: ${cmd}"
${cmd}
